In [1]:
import numpy as np
import pandas as pd

In [3]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))

def softmax(z):
    z_adjusted = z - np.max(z, axis=1, keepdims=True)
    exp_z = np.exp(z_adjusted)
    return exp_z / np.sum(exp_z, axis=1, keepdims=True)

def relu(z):
    return np.maximum(0, z)

def leaky_relu(z, alpha=0.01):
    return np.maximum(alpha * z, z)

def tanh(z):
    return (np.exp(z) - np.exp(-z)) / (np.exp(z) + np.exp(-z))

def swish(z):
    return z * sigmoid(z)

def gelu(z):
    return 0.5 * z * (1 + np.tanh(np.sqrt(2 / np.pi) * (z + 0.044715 * np.power(z, 3))))    

In [4]:
z = np.array([[-1, 2, 3], [-4, 45, 6]])
print("Sigmoid:\n", sigmoid(z))
print("Softmax:\n", softmax(z))
print("ReLU:\n", relu(z))  
print("Leaky ReLU:\n", leaky_relu(z))
print("Tanh:\n", tanh(z))
print("Swish:\n", swish(z))
print("GELU:\n", gelu(z))

Sigmoid:
 [[0.26894142 0.88079708 0.95257413]
 [0.01798621 1.         0.99752738]]
Softmax:
 [[1.32128870e-02 2.65387929e-01 7.21399184e-01]
 [5.24288566e-22 1.00000000e+00 1.15482242e-17]]
ReLU:
 [[ 0  2  3]
 [ 0 45  6]]
Leaky ReLU:
 [[-1.0e-02  2.0e+00  3.0e+00]
 [-4.0e-02  4.5e+01  6.0e+00]]
Tanh:
 [[-0.76159416  0.96402758  0.99505475]
 [-0.9993293   1.          0.99998771]]
Swish:
 [[-0.26894142  1.76159416  2.85772238]
 [-0.07194484 45.          5.98516426]]
GELU:
 [[-1.58808009e-01  1.95459769e+00  2.99636261e+00]
 [-7.02459482e-05  4.50000000e+01  6.00000000e+00]]
