In [11]:
class Car:
    def __init__(self, color, make="Toyota"):
        self.make = make
        self.color = color
        self._top_speed = 300
        self.__engine_number = "ENG12345"


    def drive(self):
        print(f"Car is driving a car of {self.make} make and {self.color} color")

    def get_engine_number(self):
        return self.__engine_number
    
    def get_top_speed(self):
        return self._top_speed

car1 = Car("Red")
car1.drive()
car1._top_speed = 350
print(f"Top speed of the car is: {car1.get_top_speed()} km/h")
# Accessing private attribute using name mangling
print(f"Engine number of the car is: {car1._Car__engine_number}")

Car is driving a car of Toyota make and Red color
Top speed of the car is: 350 km/h
Engine number of the car is: ENG12345


In [12]:
#Abstraction 
class BankAccount:
    def __init__(self, balance):
        self.__balance = balance  # private

    def deposit(self, amount):
        self.__balance += amount

    def withdraw(self, amount):
        if amount > self.__balance:
            print("Insufficient funds")
        else:
            self.__balance -= amount
    def get_balance(self):
        return self.__balance

chaitanya_account = BankAccount(1000)
chaitanya_account.deposit(500)

bibhu_account = BankAccount(2000)
bibhu_account.deposit(1000)

chaitanya_account.withdraw(200)
bibhu_account.withdraw(500) 

print(f"Chaitanya's account balance: {chaitanya_account.get_balance()}")
print(f"Bibhu's account balance: {bibhu_account.get_balance()}")

Chaitanya's account balance: 1300
Bibhu's account balance: 2500


In [ ]:
class Animal:
    def speak(self):
        print("Animal speaks")

class Dog(Animal):
    def bark(self):
        print("Dog barks")


"""
class Dog(Animal):

    def speak(self):
        print("Dog barks")

    def bark(self):
        print("Dog barks")

""" 

In [17]:
class Human:
    def __init__(self, name, age,   gender, occupation, is_married, children):
        self.name = name
        self.age = age
        self.gender = gender
        self.occupation = occupation
        self.is_married = is_married
        self.children = []
    
    def speak(self):
        print("Human speaks")
    def walk(self):
        print("Human walks")
    def eat(self):
        print("Human eats")
    def sleep(self):
        print("Human sleeps")
    def work(self):
        print("Human works")


class Girl(Human):
    def __init__(self, name, age, gender,occupation, is_married, children,hobbies,use_myntra):
        super().__init__(name, age, "Female", occupation,is_married, children)
        self.hobbies = hobbies
        self.use_myntra = use_myntra
    def speak(self):
        print("Girl speaks  softly  and sweetly")

    def cook(self):
        print("Girl cooks delicious meals")
    
chaitanya = Girl("Chaitanya", 25, "Female", "Software Engineer", False, [], ["Cooking", "Traveling"], True)
chaitanya.speak()

ramesh = Human("Ramesh", 5, "Male", "Engineer", False, [])
ramesh.speak()


Girl speaks  softly  and sweetly
Human speaks


In [4]:
class Dog:
    def sound(self):
        print("Bark")

class Cat:
    def sound(self):
        print("Meow")

for animal in [Dog(), Cat()]:
    animal.sound()

Bark
Meow


#### Exception Handling

In [2]:
a = 10
b = 0 

a/b

ZeroDivisionError: division by zero

In [3]:
a = [10, 20, 30] 
a[5]

IndexError: list index out of range

In [19]:
try:
    for i in range(5):
        for j in range(5,-2,-1):
            import keras
            print(i/j)
except ZeroDivisionError:
    print("Cannot divide by zero")
except IndexError:
    print("Index out of range")
except ModuleNotFoundError:
    print("module is not installed")
except Exception as e:
    print(f"An error occurred: {e}")
    
print("I am done with programming, I am going to sleep")


module is not installed
I am done with programming, I am going to sleep


In [13]:
for i in range(5):
        for j in range(5,-2,-1):
            print(i/j)
print("I am done with programming, I am going to sleep")


0.0
0.0
0.0
0.0
0.0


ZeroDivisionError: division by zero

In [20]:
import logging
logging.basicConfig(level=logging.INFO)

try:
    for i in range(5):
        for j in range(5,-2,-1):
            import keras
            print(i/j)
except ZeroDivisionError:
    logging.error("Cannot divide by zero")
except IndexError:
    logging.error("Index out of range")
except ModuleNotFoundError:
    logging.error("module is not installed")
except Exception as e:
    logging.error(f"An error occurred: {e}")

logging.info("I am done with programming, I am going to sleep")


ERROR:root:module is not installed
INFO:root:I am done with programming, I am going to sleep


In [24]:
try:
    a = input("Enter a number: ")
    b = input("Enter another number: ")
    result = int(a) / int(b)
    logging.info(result)
except ValueError:
    logging.error("Invalid input. Please enter valid numbers.")
except ZeroDivisionError:
    logging.error("Cannot divide by zero.")
except Exception as e:
    logging.error(f"An error occurred: {e}")

ERROR:root:Cannot divide by zero.


'pip' is not recognized as an internal or external command,
operable program or batch file.


In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)

In [18]:
df

,A,B,C,D,E,F
0,1.0,2013-01-02,1.0,3,test,foo
1,1.0,2013-01-02,1.0,3,train,foo
2,1.0,2013-01-02,1.0,3,test,foo
3,1.0,2013-01-02,1.0,3,train,foo


In [34]:
df_test = df[df['E'] == "train"].reset_index(drop=True)

In [35]:
df_test

,A,B,C,D,E,F
0,1.0,2013-01-02,1.0,3,train,foo
1,1.0,2013-01-02,1.0,3,train,foo


In [36]:
### Column Selection or Indexing
df_test['C'][0]

np.float32(1.0)

In [37]:
df_test['C'][1]

np.float32(1.0)

In [39]:
df_test[["B","C"]]

,B,C
0,2013-01-02,1.0
1,2013-01-02,1.0


In [41]:
### Loc and Iloc

In [44]:
df.loc[0, "C"]

np.float32(1.0)

In [46]:
df.loc[:,"C"]

0    1.0
1    1.0
2    1.0
3    1.0
Name: C, dtype: float32

In [47]:
df.loc[0,:]

A                    1.0
B    2013-01-02 00:00:00
C                    1.0
D                      3
E                   test
F                    foo
Name: 0, dtype: object

In [48]:
df.loc[0]

A                    1.0
B    2013-01-02 00:00:00
C                    1.0
D                      3
E                   test
F                    foo
Name: 0, dtype: object

In [57]:
filtering_condition = df["E"] == 'test'

In [58]:
df[filtering_condition]

,A,B,C,D,E,F,Z
0,1.0,2013-01-02,1.0,3,test,foo,2.0
2,1.0,2013-01-02,1.0,3,test,foo,2.0


#### Employee Database

In [114]:
employee_data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Name": [
        "Amit Sharma",
        "Priya Das",
        "Rahul Verma",
        "Sneha Patnaik",
        "Arjun Rao",
        "Neha Singh",
        "Karan Mehta",
        "Pooja Nair"
    ],
    "Age": [29, 32, 27, 35, 30, 28, 40, 31],
    "Gender": ["Male", "Female", "Male", "Female", "Male", "Female", "Male", "Female"],
    "Department": [
        "IT",
        "HR",
        "Finance",
        "Marketing",
        "IT",
        "Sales",
        "Operations",
        "Finance"
    ],
    "Designation": [
        "Software Engineer",
        "HR Manager",
        "Financial Analyst",
        "Marketing Lead",
        "Data Scientist",
        "Sales Executive",
        "Operations Manager",
        "Accountant"
    ],
    "Salary": [75000, 68000, 72000, 85000, 95000, 60000, 105000, 70000],
    "City": [
        "Bhubaneswar",
        "Delhi",
        "Mumbai",
        "Hyderabad",
        "Bengaluru",
        "Chennai",
        "Pune",
        "Kolkata"
    ],
    "Experience_Years": [5, 8, 4, 10, 6, 3, 12, 5],
    "Joining_Date": pd.to_datetime([
        "2019-06-15",
        "2016-09-10",
        "2020-01-20",
        "2014-11-05",
        "2018-07-12",
        "2021-03-18",
        "2012-08-25",
        "2019-12-01"
    ]),
    "Performance_Rating": [4.5, 4.2, 4.0, 4.8, 4.7, 3.9, 4.9, 4.1]
}

# Create DataFrame
df = pd.DataFrame(employee_data)

In [67]:
#df['Name'][5] = 'Chaitanya'
df.loc[5,'Name'] = 'Chaitanya'

In [ ]:
df['Performance_Rating'] > 4.5

0    False
1    False
2    False
3     True
4     True
5    False
6     True
7    False
Name: Performance_Rating, dtype: bool

In [115]:
df

,Employee_ID,Name,Age,Gender,Department,Designation,Salary,City,Experience_Years,Joining_Date,Performance_Rating
0,101,Amit Sharma,29,Male,IT,Software Engineer,75000,Bhubaneswar,5,2019-06-15,4.5
1,102,Priya Das,32,Female,HR,HR Manager,68000,Delhi,8,2016-09-10,4.2
2,103,Rahul Verma,27,Male,Finance,Financial Analyst,72000,Mumbai,4,2020-01-20,4.0
3,104,Sneha Patnaik,35,Female,Marketing,Marketing Lead,85000,Hyderabad,10,2014-11-05,4.8
4,105,Arjun Rao,30,Male,IT,Data Scientist,95000,Bengaluru,6,2018-07-12,4.7
5,106,Neha Singh,28,Female,Sales,Sales Executive,60000,Chennai,3,2021-03-18,3.9
6,107,Karan Mehta,40,Male,Operations,Operations Manager,105000,Pune,12,2012-08-25,4.9
7,108,Pooja Nair,31,Female,Finance,Accountant,70000,Kolkata,5,2019-12-01,4.1


In [121]:
df1 = df.loc[df['Performance_Rating'] > 4.5,:]

In [117]:
#d = df.loc[df['Performance_Rating'] > 4.5,['Gender','Designation']]

In [124]:
df1.iloc[0,2]

np.int64(35)

In [99]:
d

,Gender,Designation
3,Female,Marketing Lead
4,Male,Data Scientist
6,Male,Operations Manager


In [102]:
df.loc[3::2,'Gender']

3    Female
5    Female
7    Female
Name: Gender, dtype: object

In [103]:
### Iloc

In [107]:
df.index

RangeIndex(start=0, stop=8, step=1)

In [108]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'Gender', 'Department', 'Designation',
       'Salary', 'City', 'Experience_Years', 'Joining_Date',
       'Performance_Rating'],
      dtype='object')

In [110]:
df.index = ['a','b','c','d','e','f','g','h']

In [125]:
df

,Employee_ID,Name,Age,Gender,Department,Designation,Salary,City,Experience_Years,Joining_Date,Performance_Rating
0,101,Amit Sharma,29,Male,IT,Software Engineer,75000,Bhubaneswar,5,2019-06-15,4.5
1,102,Priya Das,32,Female,HR,HR Manager,68000,Delhi,8,2016-09-10,4.2
2,103,Rahul Verma,27,Male,Finance,Financial Analyst,72000,Mumbai,4,2020-01-20,4.0
3,104,Sneha Patnaik,35,Female,Marketing,Marketing Lead,85000,Hyderabad,10,2014-11-05,4.8
4,105,Arjun Rao,30,Male,IT,Data Scientist,95000,Bengaluru,6,2018-07-12,4.7
5,106,Neha Singh,28,Female,Sales,Sales Executive,60000,Chennai,3,2021-03-18,3.9
6,107,Karan Mehta,40,Male,Operations,Operations Manager,105000,Pune,12,2012-08-25,4.9
7,108,Pooja Nair,31,Female,Finance,Accountant,70000,Kolkata,5,2019-12-01,4.1


In [126]:
df.iloc[0:4, 2:4]

,Age,Gender
0,29,Male
1,32,Female
2,27,Male
3,35,Female


In [127]:
employee_data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Name": [
        "Amit Sharma",
        "Priya Das",
        "Rahul Verma",
        "Sneha Patnaik",
        "Arjun Rao",
        "Neha Singh",
        "Karan Mehta",
        "Pooja Nair"
    ],
    "Age": [29, 32, np.nan, 35, 30, 28, 40, 31],  # Null value added
    "Gender": ["Male", "Female", "Male", "Female", "Male", "Female", None, "Female"],  # Null value added
    "Department": [
        "IT",
        "HR",
        "Finance",
        "Marketing",
        "IT",
        None,  # Null value added
        "Operations",
        "Finance"
    ],
    "Designation": [
        "Software Engineer",
        "HR Manager",
        "Financial Analyst",
        "Marketing Lead",
        "Data Scientist",
        "Sales Executive",
        "Operations Manager",
        None  # Null value added
    ],
    "Salary": [75000, 68000, 72000, np.nan, 95000, 60000, 105000, 70000],  # Null value added
    "City": [
        "Bhubaneswar",
        "Delhi",
        "Mumbai",
        "Hyderabad",
        None,  # Null value added
        "Chennai",
        "Pune",
        "Kolkata"
    ],
    "Experience_Years": [5, 8, 4, 10, np.nan, 3, 12, 5],  # Null value added
    "Joining_Date": pd.to_datetime([
        "2019-06-15",
        "2016-09-10",
        "2020-01-20",
        None,  # Null value added
        "2018-07-12",
        "2021-03-18",
        "2012-08-25",
        "2019-12-01"
    ]),
    "Performance_Rating": [4.5, 4.2, None, 4.8, 4.7, 3.9, 4.9, 4.1]  # Null value added
}

# Create DataFrame
df = pd.DataFrame(employee_data)

In [130]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype         
---  ------              --------------  -----         
 0   Employee_ID         8 non-null      int64         
 1   Name                8 non-null      object        
 2   Age                 7 non-null      float64       
 3   Gender              7 non-null      object        
 4   Department          7 non-null      object        
 5   Designation         7 non-null      object        
 6   Salary              7 non-null      float64       
 7   City                7 non-null      object        
 8   Experience_Years    7 non-null      float64       
 9   Joining_Date        7 non-null      datetime64[ns]
 10  Performance_Rating  7 non-null      float64       
dtypes: datetime64[ns](1), float64(4), int64(1), object(5)
memory usage: 832.0+ bytes


In [133]:
df['Age'] = df['Age'].astype('float32')
df['Employee_ID'] = df['Employee_ID'].astype('int16')

In [134]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype         
---  ------              --------------  -----         
 0   Employee_ID         8 non-null      int16         
 1   Name                8 non-null      object        
 2   Age                 7 non-null      float32       
 3   Gender              7 non-null      object        
 4   Department          7 non-null      object        
 5   Designation         7 non-null      object        
 6   Salary              7 non-null      float64       
 7   City                7 non-null      object        
 8   Experience_Years    7 non-null      float64       
 9   Joining_Date        7 non-null      datetime64[ns]
 10  Performance_Rating  7 non-null      float64       
dtypes: datetime64[ns](1), float32(1), float64(3), int16(1), object(5)
memory usage: 752.0+ bytes


In [150]:
df.isna().sum()

Employee_ID           0
Name                  0
Age                   1
Gender                1
Department            1
Designation           1
Salary                1
City                  1
Experience_Years      1
Joining_Date          1
Performance_Rating    1
dtype: int64

### Imputation - Null Value Replacement - Null value Imputation

In [ ]:
## Step 1 : Identify why the data is missing, is it missing at random or not, and then decide how to handle the missing data.
## Step 2: If the data is missing at random, we can impute the missing values using mean, median, or mode.
## Step 3: If the data is not missing at random, we can either drop the rows with missing values or use advanced imputation techniques like similar value imputation/replacement.
## Note : If the amount of missing data is too much > 20%, then first check with client/stakeholder if you can drop that column, if yes then drop it, if no, Then look for row dropping or imputation using source check, similar case/value replacement

In [ ]:
TVS Jupyter - 110 - 45 
Honda Activa - 110 - 50
TVS Ntorq - 125 - 35
Hero Pleasure - 100 - 55
Honda Dio - 110 - 45
Yamaha Fascino - 110 - null

SyntaxError: invalid syntax (3278393183.py, line 1)

In [151]:
df['Age'].fillna(df['Age'].mean(), inplace=True)
df['City'].fillna(df['City'].mode()[0], inplace=True)
df['Salary'].fillna(df['Salary'].median(), inplace=True)
df['Department'].fillna(df['Department'].mode()[0], inplace=True)
df['Designation'].fillna(df['Designation'].mode()[0], inplace=True)
df['Experience_Years'].fillna(df['Experience_Years'].mean(), inplace=True)
df['Joining_Date'].fillna(df['Joining_Date'].mode()[0], inplace=True)
df['Performance_Rating'].fillna(df['Performance_Rating'].mean(), inplace=True)

C:\Users\prajn\AppData\Local\Temp\ipykernel_6840\2214987041.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)
C:\Users\prajn\AppData\Local\Temp\ipykernel_6840\2214987041.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For examp

In [152]:
df.isna().sum()

Employee_ID           0
Name                  0
Age                   0
Gender                1
Department            0
Designation           0
Salary                0
City                  0
Experience_Years      0
Joining_Date          0
Performance_Rating    0
dtype: int64

In [153]:
df.shape

(8, 11)

In [163]:
# Mean - Average
# Median - middle value when the data is sorted 
# Mode - Most frequently occurring value in the data

In [164]:
a = [1,2,3,5,6,7,9,1,11]
mean = sum(a)/len(a)
print(f"Mean: {mean}")

median = sorted(a)[len(a)//2]
print(f"Median: {median}")

mode = max(set(a), key=a.count)
print(f"Mode: {mode}")

Mean: 5.0
Median: 5
Mode: 1


In [165]:
df['Age'].mean()

np.float32(31.020407)

In [166]:
df['City'].value_counts()

City
Bhubaneswar    2
Delhi          1
Mumbai         1
Hyderabad      1
Chennai        1
Kolkata        1
Name: count, dtype: int64

### Concat and Join

In [181]:
df1= pd.DataFrame(np.random.randn(10, 4))

In [182]:
df1

,0,1,2,3
0,1.380193,-0.469750,-0.784037,0.315396
1,-1.190969,1.462219,-0.240113,0.130420
2,0.004501,-0.263305,2.133012,0.195680
3,0.864791,-1.209305,0.115605,2.335099
4,0.902684,0.248266,-0.423571,0.694898
5,1.099893,0.068493,2.640802,-1.230540
6,0.825903,0.699951,-0.876778,1.644263
7,-0.286705,1.073438,3.643192,1.224242
8,0.226901,-0.247899,0.027702,0.732306
9,-0.069400,0.402364,2.370713,-0.008724


In [183]:
df2 = pd.DataFrame(np.random.randn(10, 4))

In [184]:
df2

,0,1,2,3
0,2.203323,1.128294,-0.029699,-0.295495
1,-2.012781,-1.090308,-0.186646,0.212829
2,0.025177,0.496554,0.392898,-0.554711
3,0.802096,0.407960,-0.553768,1.359694
4,1.230361,0.279505,0.260676,-1.326991
5,0.410262,-0.061203,0.186840,-0.106309
6,-1.425819,-0.317052,-1.181180,1.877362
7,2.782451,1.047916,0.267827,-2.203419
8,-1.126140,0.265375,-0.606700,-0.039097
9,1.388671,1.125766,-1.404670,0.542272


In [186]:
pd.concat([df1, df2], axis=0).reset_index(drop=True)

,0,1,2,3
0,1.380193,-0.469750,-0.784037,0.315396
1,-1.190969,1.462219,-0.240113,0.130420
2,0.004501,-0.263305,2.133012,0.195680
3,0.864791,-1.209305,0.115605,2.335099
4,0.902684,0.248266,-0.423571,0.694898
5,1.099893,0.068493,2.640802,-1.230540
6,0.825903,0.699951,-0.876778,1.644263
7,-0.286705,1.073438,3.643192,1.224242
8,0.226901,-0.247899,0.027702,0.732306
9,-0.069400,0.402364,2.370713,-0.008724


In [188]:
pd.concat([df1, df2], axis=1).reset_index(drop=True)

,0,1,2,3,0,1,2,3
0,1.380193,-0.469750,-0.784037,0.315396,2.203323,1.128294,-0.029699,-0.295495
1,-1.190969,1.462219,-0.240113,0.130420,-2.012781,-1.090308,-0.186646,0.212829
2,0.004501,-0.263305,2.133012,0.195680,0.025177,0.496554,0.392898,-0.554711
3,0.864791,-1.209305,0.115605,2.335099,0.802096,0.407960,-0.553768,1.359694
4,0.902684,0.248266,-0.423571,0.694898,1.230361,0.279505,0.260676,-1.326991
5,1.099893,0.068493,2.640802,-1.230540,0.410262,-0.061203,0.186840,-0.106309
6,0.825903,0.699951,-0.876778,1.644263,-1.425819,-0.317052,-1.181180,1.877362
7,-0.286705,1.073438,3.643192,1.224242,2.782451,1.047916,0.267827,-2.203419
8,0.226901,-0.247899,0.027702,0.732306,-1.126140,0.265375,-0.606700,-0.039097
9,-0.069400,0.402364,2.370713,-0.008724,1.388671,1.125766,-1.404670,0.542272


#Join

In [189]:
left = pd.DataFrame({"key": ["foo", "foo"], "lval": [1, 2]})
right = pd.DataFrame({"key": ["foo", "foo"], "rval": [4, 5]})
pd.merge(left, right, on="key",how='inner')

,key,lval,rval
0,foo,1,4
1,foo,1,5
2,foo,2,4
3,foo,2,5


In [190]:
import pandas as pd

employees = pd.DataFrame({
    'Emp_ID': [101, 102, 103, 104, 105, 106],
    'Name': ['Aman', 'Priya', 'Rahul', 'Sneha', 'Karan', 'Neha'],
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR', 'Finance'],
    'Salary': [60000, 45000, 70000, 50000, 48000, 52000]
})


projects = pd.DataFrame({
    'Emp_ID': [101, 102, 103, 105, 107],
    'Project': ['AI Bot', 'Recruitment App', 'Cloud Migration', 'Training Portal', 'Security Audit'],
    'Hours_Worked': [120, 80, 150, 95, 110]
})

In [191]:
pd.merge(employees, projects, on='Emp_ID', how='inner')

,Emp_ID,Name,Department,Salary,Project,Hours_Worked
0,101,Aman,IT,60000,AI Bot,120
1,102,Priya,HR,45000,Recruitment App,80
2,103,Rahul,IT,70000,Cloud Migration,150
3,105,Karan,HR,48000,Training Portal,95


In [197]:
employees.merge(projects, on='Emp_ID', how='left')

,Emp_ID,Name,Department,Salary,Project,Hours_Worked
0,101,Aman,IT,60000,AI Bot,120.0
1,102,Priya,HR,45000,Recruitment App,80.0
2,103,Rahul,IT,70000,Cloud Migration,150.0
3,104,Sneha,Finance,50000,NaN,NaN
4,105,Karan,HR,48000,Training Portal,95.0
5,106,Neha,Finance,52000,NaN,NaN


In [198]:
df = pd.DataFrame(
    {
        "A": ["foo", "bar", "foo", "bar", "foo", "bar", "foo", "foo"],
        "B": ["one", "one", "two", "three", "two", "two", "one", "three"],
        "C": np.random.randn(8),
        "D": np.random.randn(8),
    }
)


In [199]:
df

,A,B,C,D
0,foo,one,-0.261346,-0.050550
1,bar,one,0.594687,1.998790
2,foo,two,0.766390,-0.980870
3,bar,three,-1.964078,0.989734
4,foo,two,-0.094378,-0.217986
5,bar,two,-1.883138,0.798504
6,foo,one,-1.179088,1.562082
7,foo,three,3.971136,0.358766


In [213]:
df.groupby("A").get_group("foo")[['C','D']].sum()

C    3.202715
D    0.671442
dtype: float64

In [ ]:
df.groupby("A")[["C", "D"]].sum()

,C,D
A,,
bar,-3.252530,3.787028
foo,3.202715,0.671442


In [201]:
df.groupby(["A", "B"]).sum()

C         D
A   B                        
bar one    0.594687  1.998790
    three -1.964078  0.989734
    two   -1.883138  0.798504
foo one   -1.440434  1.511532
    three  3.971136  0.358766
    two    0.672013 -1.198856

In [202]:
df.groupby(["A", "B"]).sum()

C         D
A   B                        
bar one    0.594687  1.998790
    three -1.964078  0.989734
    two   -1.883138  0.798504
foo one   -1.440434  1.511532
    three  3.971136  0.358766
    two    0.672013 -1.198856

In [217]:
employees.head()

,Emp_ID,Name,Department,Salary
0,101,Aman,IT,60000
1,102,Priya,HR,45000
2,103,Rahul,IT,70000
3,104,Sneha,Finance,50000
4,105,Karan,HR,48000


In [215]:
employees.groupby("Department")["Salary"].mean()

Department
Finance    51000.0
HR         46500.0
IT         65000.0
Name: Salary, dtype: float64

In [219]:
pd.merge(employees, projects, on='Emp_ID', how='inner').groupby("Department")["Salary"].mean()

Department
HR    46500.0
IT    65000.0
Name: Salary, dtype: float64

In [220]:
pd.pivot_table(employees, values="Salary", index=["Department"], columns=["Emp_ID"])

Emp_ID,101,102,103,104,105,106
Department,,,,,,
Finance,NaN,NaN,NaN,50000.0,NaN,52000.0
HR,NaN,45000.0,NaN,NaN,48000.0,NaN
IT,60000.0,NaN,70000.0,NaN,NaN,NaN


In [225]:
In [117]: df = pd.DataFrame(
   .....:     {"id": [1, 2, 3, 4, 5, 6], "raw_grade": ["a", "b", "b", "a", "a", "e"]})

In [222]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   id         6 non-null      int64 
 1   raw_grade  6 non-null      object
dtypes: int64(1), object(1)
memory usage: 224.0+ bytes


In [226]:
df["raw_grade"] = df["raw_grade"].astype("category")

In [227]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype   
---  ------     --------------  -----   
 0   id         6 non-null      int64   
 1   raw_grade  6 non-null      category
dtypes: category(1), int64(1)
memory usage: 314.0 bytes


#### Numpy

### What is the main advantage of NumPy over Python Lists?

NumPy arrays are faster, consume less memory, and support vectorized operations, making them ideal for Data Science and Machine Learning.

In [39]:
import numpy as np
import sys

li = list(range(10000000))
arr = np.array(li)

print(arr)
print(sys.getsizeof(arr))
print(sys.getsizeof(li))

[      0       1       2 ... 9999997 9999998 9999999]
80000112
80000056


In [40]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr2)

[[1 2 3]
 [4 5 6]]


In [41]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr.shape)
print(arr.ndim)
print(arr.size)

(2, 3)
2
6


In [27]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [48]:
np.linspace(0,3,4)

array([0., 1., 2., 3.])

In [49]:
arr = np.arange(1,13)

arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
arr = np.array([10,20,30,40,50])

print(arr[0])
print(arr[-1])

10
50


In [35]:
print(arr[1:4])

[20 30 40]


In [15]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr[0,1])

2


In [17]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
arr = np.array([10,20,30,40])

print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr)) #Measure of spread of the data, how much the data is spread out from the mean, higher the std, more spread out the data is, lower the std, less spread out the data is

100
25.0
40
10
11.180339887498949


In [19]:
np.random.rand(3)

array([0.82535611, 0.04088273, 0.1298968 ])

In [20]:
np.random.randint(1,100,5)

array([42, 45, 98,  1, 11], dtype=int32)

In [21]:
arr = np.array([10,20,30,40,50])

print(arr > 25)

[False False  True  True  True]


In [22]:
arr[arr > 25]

array([30, 40, 50])

In [23]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr.sum(axis=0))

[5 7 9]
